### ISSUE TITLE
Change current api to get presigned urls

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-s3-integration#1]
**Is your feature request related to a problem? Please describe.**

The API has to be changed from file driven HTTP-API to an API which provides an S3 presigned url for save, delete, update, read functionality.

**Describe the solution you'd like**

Implement REST-Endpoints (GET, PUT, POST, DELETE) to get presigned urls for a file identified with the information given in the Rest parameters

**Additional context**
n/a

**Comment by boal** [comment]
implements appropriate logging points in cope
