### ISSUE TITLE
Add scheduled job for deletion of db entries for in s3 deleted folders

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-s3-integration#16]
**Is your feature request related to a problem? Please describe.**

Because when we create the presigned url for deleting the file, we don't know if the file will really be deleted by a request over the url.

If it is the last file in the folder, S3 automatically deletes the folder as well. However the folder tag in the database is not deleted.

**Describe the solution you'd like**

Add method for scheduling into class S3AndDatabaseCleanupService.

**Describe alternatives you've considered**
tbd

**Additional context**
tbd

**Comment by boal** [comment]
Add method for scheduling into class ```S3AndDatabaseCleanupService```:

**Comment by dominikhorn93** [comment]
@boal this is done via https://github.com/it-at-m/digiwf-s3-integration/blob/dev/digiwf-s3-integration-starter/src/main/java/io/muenchendigital/digiwf/s3/integration/configuration/CleanUpJobConfiguration.java or not?

**Comment by boal** [comment]
Yes, not exactly. This cron job deletes all folder (with all containing files) for which the end of life is exceeded.

The new additional cron job deltes folder entries within the database which dont exists in S3.
