### ISSUE TITLE
Add OpenAPI Annotations to API Object

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-s3-integration#17]
**Is your feature request related to a problem? Please describe.**
When using the OpenAPI Definition it is not clear what the controllers, methods and dtos are all about.

**Describe the solution you'd like**
We should add OpenAPI annotations to have a better documentation.
- @Tag(name = "abc") for Controllers
- @Operation(summary = "abc") for methods
- @Schema(description = "abc") for DTOs

**Comment by boal** [comment]
Issue to change name of FileResponseDto to PresingedUrlDto.

https://github.com/it-at-m/digiwf-s3-integration/issues/23
