### ISSUE TITLE
Provide an OpenAPI Client example

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-s3-integration#21]
**Is your feature request related to a problem? Please describe.**
tbd.

**Describe the solution you'd like**
tbd.

**Comment by boal** [comment]
@dominikhorn93 

The example for the service exposes already an openapi description.

Within the pom for digiwf-s3-integration-client, an client is used to generate the client side code.

I think the readme should describe the generation within the client. A description for the openapi endpoints is already described.

**Comment by boal** [comment]
The `digiwf-s3-integration-client-starter` is using the generated client based on the openapi description from `digiwf-s3-integration-starter`.
