### ISSUE TITLE
Build pipeline for maven central

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-s3-integration#4]
**Is your feature request related to a problem? Please describe.**
Currently, the spring boot starter is not provided in maven central. This needs to be adapted to be able to use it in other projects.

**Describe the solution you'd like**
We need to set up a pipeline and automatically deploy the artifact to maven central on a push to the main branch.

**Additional context**
There are a few things to do to be able to perform this:

- [ ] create a maven central account https://central.sonatype.org/publish/publish-guide/#introduction
- [ ] create a GitHub Action Pipeline (we need to store the certificate to sign the artifacts in GitHub)

**Comment by dominikhorn93** [comment]
@xdoo which e-mail address should I use for the maven central account?
I guess many of us should have access to it?

**Comment by xdoo** [comment]
Can we add mail to the muenchendigital.io domain?

**Comment by dominikhorn93** [comment]
Sure. I am going to add a mail server and configure forwarding to our internal mailboxes. 👍

**Comment by dominikhorn93** [comment]
> Can we add mail to the muenchendigital.io domain?

We will use opensource@muenchendigital.io

**Comment by dominikhorn93** [comment]
Using this GitHub action: https://github.com/marketplace/actions/action-maven-publish
