### ISSUE TITLE
Return too many files when folder names resemble

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-s3-integration#45]
**Describe the bug**
When one file is uploaded to folder "someFileContext/someFieldKey/someFilename.png" and the second is uploaded to "someFileContext/someFieldKey2/someOtherFilename.png", the folder-Api-Endpoint returns both files, when asked for "someFileContext/someFieldKey"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by boal** [comment]
Cause found:

Within the file database and even within the s3 storage, the file path is just a string and not a file and folder hierarchy.

In Method "FolderHandlingService.deleteFolder" and "FolderHandlingService.getAllFilesInFolderRecursively" the parameter "pathToFolder" is used for an prefix search on the string representing the paht to the file.

The prefix string "someFileContext/someFieldKey" is matching "someFileContext/someFieldKey2/someOtherFilename.png" and  "someFileContext/someFieldKey/someFilename.png".

Solution as suggested from @martind260 is the add a "/" (path seperator) if this seperator is not existing at the end of the index string.

**Comment by boal** [comment]
Released with Version 0.0.3
